### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by Rijwandeltax** [smichelotti/star-wars-name-game#4]
i have a error in this code when i run this  

Error: Cannot find module 'D:\ionic\star-wars-name-game-master\node_modules\@ionic\app-scripts'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Unique\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic-angular\app-scripts.js:9:16)
    at Generator.next (<anonymous>)
    at C:\Users\Unique\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:105:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Unique\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:101:16)
    at Object.importAppScripts (C:\Users\Unique\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic-angular\app-scripts.js:7:20)

**Comment by smichelotti** [comment]
this was created with an older version of Ionic. You probably have a more updated Ionic CLI. Feel free to submit PR.
